print('VScode 사용 시 git과 연동하고자 하는 폴더에서 Terminal 명령어로 다음과 같이 시작한다.')
print('git init')
print()
print('소스 코드를 작성한 뒤 저장하면 Source control 패널에서 unstaged 파일로 등록이 된다.')
print('stage로 이동시키기 위해서 + 버튼을 누르거나 Terminal 명령어로 다음과 같이 입력한다.')
print('git add 파일명.py')
print()
print('stage로 이동한 파일은 comment를 입력한 뒤 commit 버튼을 누르거나 Terminal 명령어로 다음과 같이 입력한다.')
print('git commit -m "코멘트"')
print()